### ISSUE TITLE
Lorsque l'on passe une Commune inexistanteon récupère une erreur 500

### ISSUE THREAD

**Issue by meilie389** [adriens/opt-temps-attente-agences-api#1]
# Sumptôme

Erreur 500 lors de la recherche d'agences par nom de commune inexistante.
/temps-attente/agences/toto

# Comportement attendu

renvoyer une `404` dans ce cas

**Comment by meilie389** [comment]
![temps-attente-Capture du 2020-03-23 13-39-10](https://user-images.githubusercontent.com/41884305/77275149-b6f81180-6d0b-11ea-874c-21830eb09781.png)
On renvoie une erreur 404 lors de la saisie d'un mauvais nom de commune

**Comment by adriens** [comment]
YES !
