### ISSUE TITLE
envoyer latitude et longitude

### ISSUE THREAD

**Issue by adriens** [adriens/opt-temps-attente-agences-api#10]
Cela sera vraiment utile, j'ai commencé à designer quelque'chose 😸 

Si possible, envoyer en X,Y, mais c'est bonus, pas sûr qu'on les ait...

**Comment by meilie389** [comment]
![tempsattente-Capture du 2020-03-23 12-58-41](https://user-images.githubusercontent.com/41884305/77272923-734ed900-6d06-11ea-8bd8-3a8180db5c79.png)
Envoi des coordonnées X et Y (décimales) et des coordonnées X et Y précises (entiers) des champs coordonneesXyRefloc et coordonneesXyPrecisesRefloc par le SDK

**Comment by adriens** [comment]
Clean
