### ISSUE TITLE
idAgence est typé comme String...au lieu de nombre entier

### ISSUE THREAD

**Issue by adriens** [adriens/opt-temps-attente-agences-api#13]

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/76675885-56354e80-6612-11ea-8c96-2a17b259bba8.png)

**Comment by meilie389** [comment]
![TEMPSATTENTE-Capture du 2020-03-23 12-56-07](https://user-images.githubusercontent.com/41884305/77272828-3c78c300-6d06-11ea-9660-778b2d18688d.png)
Modification effetuée dans le sdk

**Comment by adriens** [comment]
Clean @meilie389 👍
