### ISSUE TITLE
Infos reponse api - realMaxWaitingTime : renommage du champ

### ISSUE THREAD

**Issue by joaquimaffre-opt** [adriens/opt-temps-attente-agences-api#2]
Permettre d'identifier l'unité de temps de `realMaxWaitingTime`
- Exemple la renommer en `realMaxWaitingTimeMs`

**Comment by adriens** [comment]
Excellente idée @joaquimaffre-opt , @meilie389 , on retouchera le `SDK` et généraliserons l'approche afin de rendre es chmaps plus parlants.

**Comment by adriens** [comment]
Ok, on va faire le nécessaire dans le SDK cf issue liée et ce sra OK.
On appliqera la même nomenclature pour les autres champs 👍 
Ensuite, on documentera l'API et on  sera opérationels pour accueililr des clients 👏

**Comment by adriens** [comment]
http://localhost:8080/temps-attente/agence/4314


![image](https://user-images.githubusercontent.com/5235127/76657219-74289200-65c5-11ea-819e-9e3ffd5b2e7a.png)

**Comment by adriens** [comment]
Ok, je vais passer au déploiement cf  Déployer sur Heroku #5
