### ISSUE TITLE
Cas où l'identifiant de l'agence n'existe pas

### ISSUE THREAD

**Issue by HakumenNC** [adriens/opt-temps-attente-agences-api#3]
Bonjour,
Lorsque l'on met un `id` d'une agence qui n'existe pas, l'api retourne un objet *vide* :

Exemple : `http://localhost:8080/temps-attente/agence/123456879`

```json
{
    "idAgence": "",
    "designation": "",
    "realMaxWaitingTime": 0
}
```
L'idéal (à mon avis) serait de renvoyer une erreur `404`.

Merci

**Comment by adriens** [comment]
`404` semble parfaitement adapté, très bien vu @HakumenNC 👍

**Comment by meilie389** [comment]
![temps-attente-Capture du 2020-03-23 13-37-20](https://user-images.githubusercontent.com/41884305/77275071-7a2c1a80-6d0b-11ea-86ae-92fe44a448d1.png)
On renvoie une erreur 404 lors de la saisie d'un mauvais id d'agence
