### ISSUE TITLE
Répondre quelque'chose sur /

### ISSUE THREAD

**Issue by adriens** [adriens/opt-temps-attente-agences-api#8]
http://localhost:8080/

![image](https://user-images.githubusercontent.com/5235127/76658891-2e6dc880-65c9-11ea-9809-de4b98057581.png)

Par exemplle pointer vers une page de doc, genre le README sur Github ;-p

**Comment by meilie389** [comment]
localhost:8080/ redirige vers 
https://github.com/adriens/opt-temps-attente-agences-api/blob/master/README.md

**Comment by adriens** [comment]
Stp, renvoies juste sur

https://github.com/adriens/opt-temps-attente-agences-api

**Comment by meilie389** [comment]
localhost:8080/ redirige vers
https://github.com/adriens/opt-temps-attente-agences-api/
